//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BancoNM
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Prestamos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Prestamos()
        {
            this.PagoPrestamos = new HashSet<PagoPrestamos>();
        }
        
        [DisplayName("Id Préstamo")]
        public int idPrestamo { get; set; }
        [DisplayName("Id del Cliente")]
        public Nullable<int> idCliente { get; set; }
        [DisplayName("Monto")]
        public Nullable<decimal> monto { get; set; }
        [DisplayName("Plazo")]
        public Nullable<int> plazo { get; set; }
        [DisplayName("Taza Anual")]
        public Nullable<int> tazaPorcAnual { get; set; }
        [DisplayName("Cuotas Mensuales")]
        public Nullable<decimal> cuotasM { get; set; }
    
        public virtual Clientes Clientes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PagoPrestamos> PagoPrestamos { get; set; }
    }
}
